ku create deploy nginx-deployment --image=nginx:latest --replicas 6

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-deployment-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx-deployment
