#K8S Secret can be assigned using Env Variable
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-1
spec:
  containers:
    - name: aws-cli-container
      image: sreeharshav/utils:latest
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: accesskey
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: secretkey
            key: AWS_SECRET_ACCESS_KEY

#K8S Secret can be mounted as a volume
#Mount AWS Credentails as a volume
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-2
spec:
  containers:
    - name: aws-cli-container
      image: sreeharshav/utils:latest
      volumeMounts:
        - name: secret-volume
          mountPath: /root/.aws/credentials
          subPath: credentials
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-creds-in-file

------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-3
spec:
  containers:
    - name: aws-cli-container
      image: sreeharshav/utils:latest
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-access-keys
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-access-keys
            key: AWS_SECRET_ACCESS_KEY
