apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  relicas: 3
  selector:
    matchLables:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      lables:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports: 
            - containerPort: 3306
              name: mysql
          volumeMounts:
           - name: mysql-persistent-storage
             path: /var/lib/mysql
           - name: usermanagement-dbcreation-script
             path: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          presistentVolumeClaim:
            claimName: ebs-mysql-pv-claim
            