apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
  labels:
    runon: fargate 
  namespace: ns-ums
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS usermgmt;
    CREATE DATABASE usermgmt; 