apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
  tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234