apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp02
  name: nodeselector-myapp02
  annotations: 
    star: "Leo"
    company: "ATOS Syntel"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp02
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate
      nodeSelector:
        kubernetes.io/hostname: ip-172-20-63-184.ec2.internal