apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp01
  name: myapp01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate
      nodeSelector:
        perf: high