apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx001-hard
  name: nginx001-hard
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx001-hard
  template:
    metadata:
      labels:
        app: nginx001-hard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: #HARD
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - prod
                - dev
              - key: application
                operator: In
                values:
                - app1
                - app3
      containers:
      - image: nginx:latest
        name: nginx