apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx001-soft
  name: nginx001-soft
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx001-soft
  template:
    metadata:
      labels:
        app: nginx001-soft
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: #SOFT
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - prod
                - dev
              - key: application
                operator: In
                values:
                - app1
      containers:
      - image: nginx:latest
        name: nginx