kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-1
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sreeharshav/rollingupdate:v3
        ports:
        - containerPort: 80
        volumeMounts:
          - name: efs-pvc
            mountPath: /tmp/efsvol
      volumes:
         - name: efs-pvc
           persistentVolumeClaim:
              claimName: efs-1