apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod1
  name: testpod1
spec:
  containers:
    - image: nginx:latest
      name: testpod1
      resources:
        requests:
          memory: 100Mi
          cpu:  100m
        limits:
          memory: 200Mi
          cpu: 300m