apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx001
  name: nginx-np
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32195
  selector:
    app: nginx001
  type: NodePort