apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx001
  name: nginx001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx001
  template:
    metadata:
      labels:
        app: nginx001
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v5
        name: rollingupdate