apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddeploy-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - red.timibanianu.xyz
    secretName: nginx0-tls-default
  rules:
  - host: red.timibanianu.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddeploy
            port:
              number: 80
              
 ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greendeploy-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - green.timibanianu.xyz
    secretName: nginx0-tls-default
  rules:
  - host: green.timibanianu.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greendeploy
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluedeploy-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blue.timibanianu.xyz
    secretName: nginx0-tls-default
  rules:
  - host: blue.timibanianu.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bluedeploy
            port:
              number: 80
