https://www.fadhil-blog.dev/blog/kubernetes-external-ip/

#External
apiVersion: v1
kind: Service
metadata:
  name: mygoogle
spec:
  type: ExternalName
  externalName: www.google.com

#Exposing one of node public IP
---
apiVersion: v1
kind: Service
metadata:
  name: from-external
spec:
  selector:
    app: nginx001
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 80
  externalIPs:
    - 18.208.183.221