apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: msql
    containers:
      - name: mysql
        image: mysql:5.6
        ports:
          - containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: db-password
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: usermanagment-dbcreation-script
            mountPath: /docker-entrypoint-initdb.db          
    volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim
      - name: usermanagment-dbcreation-script
        configMap:
          name: usermanagement-dbcreation-script
