apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
        - name: notification-service
          image: stacksimplify/kube-notifications-microservice:1.0.0
          ports:
            - containerPort: 8096
          imagePullPolicy: Always
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "smtp-service"
            - name: AWS_MAIL_SERVER_USERNAME
              value: "AKIA2GQEGL4ONHCBW6UV"
            - name: AWS_MAIL_SERVER_PASSWORD
              value: "BAIlHor0Q2S4fb0DH9aKbZUbcFLYMmq92uwdmrm1GD85"
            - name: AWS_MAIL_SERVER_FROM_ADDRESS
              value: "pratharaj.4ever@gmail.com"